"""empty message

Revision ID: 01212242534b
Revises: 210b2cdbc0eb
Create Date: 2016-09-19 18:04:09.786348

"""

# revision identifiers, used by Alembic.
revision = '01212242534b'
down_revision = '210b2cdbc0eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('update_idx', 'update_request', ['install_id', 'query_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('update_idx', table_name='update_request')
    ### end Alembic commands ###
