"""empty message

Revision ID: 210b2cdbc0eb
Revises: None
Create Date: 2016-09-19 16:11:59.403266

"""

# revision identifiers, used by Alembic.
revision = '210b2cdbc0eb'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('query_time', sa.DateTime(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('install_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_request')
    ### end Alembic commands ###
