"""empty message

Revision ID: 752303968bbf
Revises: 01212242534b
Create Date: 2016-11-21 10:19:04.478167

"""

# revision identifiers, used by Alembic.
revision = '752303968bbf'
down_revision = '01212242534b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('date_idx', 'update_request', ['query_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date_idx', table_name='update_request')
    ### end Alembic commands ###
